#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UI.Resource", IsApplication=true)]

namespace UI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::CC.Resource.String.library_name = global::UI.Resource.String.library_name;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::UI.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::UI.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::UI.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int categorieArray = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int lichaamstypeArray = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int rolArray = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int seizoenstypeArray = 2131099650;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BlackEye = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BlackHair = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BlackSkin = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int BlueEye = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int BrownEye = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int BrownSkin = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int DarkBlondHair = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int DarkBrownHair = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int DarkGreyHair = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ectomorph = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int endomorph = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Gorilla = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int GreenEye = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int GreyEye = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int LightBlondHair = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int LightBrownHair = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int LightGreyHair = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int MediumBlondHair = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int MediumBrownHair = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int mesomorph = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int QRCode = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int WhiteSkin = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070036
			public const int btnCancelRegister = 2131165238;
			
			// aapt resource value: 0x7f070042
			public const int btnCancelToevoegenVerkoper = 2131165250;
			
			// aapt resource value: 0x7f07001d
			public const int btnEctomorph = 2131165213;
			
			// aapt resource value: 0x7f07001f
			public const int btnEndomorph = 2131165215;
			
			// aapt resource value: 0x7f070009
			public const int btnKoppelenKledingadvies = 2131165193;
			
			// aapt resource value: 0x7f070030
			public const int btnLogin = 2131165232;
			
			// aapt resource value: 0x7f07001e
			public const int btnMesomorph = 2131165214;
			
			// aapt resource value: 0x7f070041
			public const int btnOpslaanVerkoper = 2131165249;
			
			// aapt resource value: 0x7f07000a
			public const int btnScanQRCode = 2131165194;
			
			// aapt resource value: 0x7f07002c
			public const int btnSignIn = 2131165228;
			
			// aapt resource value: 0x7f07002f
			public const int btnSignUp = 2131165231;
			
			// aapt resource value: 0x7f070004
			public const int btnTerugNaarMain = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int btnToevoegenProduct = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int btnToevoegenVerkoper = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int btnTonenKledingadvies = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int btnVaststellenKledingadvies = 2131165185;
			
			// aapt resource value: 0x7f070044
			public const int btnZoekProducten = 2131165252;
			
			// aapt resource value: 0x7f070024
			public const int btn_black_eyes = 2131165220;
			
			// aapt resource value: 0x7f070018
			public const int btn_black_hair = 2131165208;
			
			// aapt resource value: 0x7f07001b
			public const int btn_black_skin = 2131165211;
			
			// aapt resource value: 0x7f070020
			public const int btn_blue_eyes = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int btn_brown_eyes = 2131165217;
			
			// aapt resource value: 0x7f07001a
			public const int btn_brown_skin = 2131165210;
			
			// aapt resource value: 0x7f070010
			public const int btn_dark_blond_hair = 2131165200;
			
			// aapt resource value: 0x7f070014
			public const int btn_dark_brown_hair = 2131165204;
			
			// aapt resource value: 0x7f070017
			public const int btn_dark_grey_hair = 2131165207;
			
			// aapt resource value: 0x7f070022
			public const int btn_green_eyes = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int btn_grey_eyes = 2131165219;
			
			// aapt resource value: 0x7f07000e
			public const int btn_light_blond_hair = 2131165198;
			
			// aapt resource value: 0x7f070012
			public const int btn_light_brown_hair = 2131165202;
			
			// aapt resource value: 0x7f070016
			public const int btn_light_grey_hair = 2131165206;
			
			// aapt resource value: 0x7f07000f
			public const int btn_medium_blond_hair = 2131165199;
			
			// aapt resource value: 0x7f070013
			public const int btn_medium_brown_hair = 2131165203;
			
			// aapt resource value: 0x7f070037
			public const int btn_open_camera = 2131165239;
			
			// aapt resource value: 0x7f07003e
			public const int btn_opslaan = 2131165246;
			
			// aapt resource value: 0x7f070019
			public const int btn_white_skin = 2131165209;
			
			// aapt resource value: 0x7f070047
			public const int contentFrame = 2131165255;
			
			// aapt resource value: 0x7f070046
			public const int imageButtonPlaceholder = 2131165254;
			
			// aapt resource value: 0x7f07000b
			public const int imageView1 = 2131165195;
			
			// aapt resource value: 0x7f07003a
			public const int inv_categorie = 2131165242;
			
			// aapt resource value: 0x7f07003d
			public const int inv_korting = 2131165245;
			
			// aapt resource value: 0x7f070039
			public const int inv_naam = 2131165241;
			
			// aapt resource value: 0x7f07003c
			public const int inv_prijs = 2131165244;
			
			// aapt resource value: 0x7f07000d
			public const int linearLayout1 = 2131165197;
			
			// aapt resource value: 0x7f070011
			public const int linearLayout2 = 2131165201;
			
			// aapt resource value: 0x7f070015
			public const int linearLayout3 = 2131165205;
			
			// aapt resource value: 0x7f07001c
			public const int linearLayout4 = 2131165212;
			
			// aapt resource value: 0x7f070003
			public const int relativeLayout1 = 2131165187;
			
			// aapt resource value: 0x7f07002d
			public const int relativeLayout2 = 2131165229;
			
			// aapt resource value: 0x7f07003b
			public const int spinner1 = 2131165243;
			
			// aapt resource value: 0x7f070035
			public const int spinner2 = 2131165237;
			
			// aapt resource value: 0x7f070028
			public const int spinnerLichaamstype = 2131165224;
			
			// aapt resource value: 0x7f070025
			public const int spinnerProduct = 2131165221;
			
			// aapt resource value: 0x7f070027
			public const int spinnerSeizoenstype = 2131165223;
			
			// aapt resource value: 0x7f070043
			public const int spinner_categorieproduct = 2131165251;
			
			// aapt resource value: 0x7f07002e
			public const int textView1 = 2131165230;
			
			// aapt resource value: 0x7f070045
			public const int txtCategorie = 2131165253;
			
			// aapt resource value: 0x7f07002a
			public const int txtEmailLogin = 2131165226;
			
			// aapt resource value: 0x7f070033
			public const int txtEmailRegister = 2131165235;
			
			// aapt resource value: 0x7f070040
			public const int txtEmailVerkoper = 2131165248;
			
			// aapt resource value: 0x7f070000
			public const int txtKlantScherm = 2131165184;
			
			// aapt resource value: 0x7f070029
			public const int txtLichaamstype = 2131165225;
			
			// aapt resource value: 0x7f07000c
			public const int txtLoginScherm = 2131165196;
			
			// aapt resource value: 0x7f07002b
			public const int txtPasswordLogin = 2131165227;
			
			// aapt resource value: 0x7f070034
			public const int txtPasswordRegister = 2131165236;
			
			// aapt resource value: 0x7f070032
			public const int txtRegisterAccount = 2131165234;
			
			// aapt resource value: 0x7f070026
			public const int txtSeizoenstype = 2131165222;
			
			// aapt resource value: 0x7f070008
			public const int txtStylistScherm = 2131165192;
			
			// aapt resource value: 0x7f07003f
			public const int txtToevoegenVerkoper = 2131165247;
			
			// aapt resource value: 0x7f070005
			public const int txtVerkopersScherm = 2131165189;
			
			// aapt resource value: 0x7f070031
			public const int txt_output = 2131165233;
			
			// aapt resource value: 0x7f070038
			public const int txt_uitleg = 2131165240;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int GebruikerKlant = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int GebruikerOndernemer = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int GebruikerStylist = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int GebruikerVerkoper = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int GenereerQRCode = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int KledingadviesHaar = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int KledingadviesHuid = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int KledingadviesLichaamstype = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int KledingadviesOog = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int KoppelenProduct = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int LoginIn = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int Main = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int QRScannen = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int SignUp = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int ToevoegenProductUI = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int ToevoegenVerkoper = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int TonenKledingadvies = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int zxingscanneractivitylayout = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int zxingscannerfragmentlayout = 2130968594;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int IconOld = 2130903041;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int categoriePrompt = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int gebruikerPrompt = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int lichaamstypePrompt = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int productPrompt = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int seizoestypePrompt = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
